Magickbase/ckb-explorer-frontend

Dockerfile
Avoid automatic reporting of data to our servers on individual deployments.
=> feat: remove the unreasonable default args

.gitignore, src/pages/BlockDetail/index.tsx, src/pages/NervosDao/index.tsx, src/pages/SimpleUDT/index.tsx, src/pages/Tokens/index.tsx, src/utils/hook.ts
This PR use the backend's page size for pagination in UI.
For more details, please see: https://github.com/Magickbase/ckb-explorer-public-issues/issues/356
=> refactor: use backend page size for pagination

src/pages/Script/ScriptsComp.tsx, src/pages/Transaction/TransactionCell/index.tsx, src/pages/Transaction/TransactionCellList/index.tsx, src/pages/Transaction/TransactionCellScript/index.tsx, src/pages/Transaction/TransactionComp.tsx
This commit fixes a bug that details of a cell are not updated when the transaction is pending
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/401
---
Before:
After:
=> fix: update detail of cells even the transaction is pending

.github/workflows/pr-from-forked-to-origin.yml
This PR adds a GitHub action to open a PR from forked/develop to origin/develop by setting `IS_SYNCED_TO_ORIGIN_REPO = true` at `/settings/variables/actions`
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/414
=> ci: add an action to merge forked/develop to origin/develop

src/pages/NervosDao/index.tsx
Fallback 'tab' to 'transactions' instead of defining a new variable named 'daoTab'
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/244#issuecomment-1696722619
=> fix: fix undefined tab on nervos dao page

src/locales/zh.json
Placeholder should be "交易/地址" but not "地址"
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/421
Preview: https://ckb-explorer-frontend-in-magickbase-repo-git-e79f3c-magickbase.vercel.app/sudt/0x788c79191970e313693351531930b46a708b1ca58f6d414ddc8a8827afb554ff
=> fix: fix placeholder of search field on sudt detail page

src/pages/Tokens/index.tsx
Some token information is incomplete so should not provide a link jump on the token list page
reslove https://github.com/Magickbase/ckb-explorer-public-issues/issues/416
related chat: https://github.com/Magickbase/ckb-explorer-public-issues/issues/416#issuecomment-1694996372
=> fix: disable link incomplete tokens

src/pages/Script/index.tsx, src/pages/Script/styles.module.scss, src/pages/Script/types.ts
show the `type id` in detail page of script from `id` property in response
=> feat(typeId): show type id from the property "id" in response

src/components/Pagination/styled.tsx, src/pages/Script/ScriptsComp.tsx, src/pages/Script/styles.module.scss, src/pages/Script/types.ts
reference: https://github.com/Magickbase/ckb-explorer-public-issues/issues/440
=> Fix: missed pagination from the page of transactions, referring cells and deployed cells. 

src/pages/StatisticsChart/block/AverageBlockTime.tsx
The data of each item is an array of string, but it's asserted to be a string while the exception is not handled properly.
=> fix: fix frozen avg-block-time chart

src/components/Banner/HalvingBanner.tsx, src/pages/Halving/index.tsx, src/utils/hook.ts
Before this PR, the countdown shows "Coming soon" after `Halving Countdown 0 Seconds", it's a bit confusing because "Halvd" is expected when the countdown lefts 0s.
This PR moves the threshold of "Coming soon" to 3s as a buffer.
https://github.com/Magickbase/ckb-explorer-frontend/assets/7271329/5a5670e2-0383-402f-a041-ddcf58623696
=> feat: update threshold of halving countdown

src/locales/en.json, src/pages/Halving/index.tsx, src/utils/hook.ts
The previous calculation of the blocks where halving occurs used the theoretical value of 1800, which was changed to the actual number of blocks
reslove: https://github.com/Magickbase/ckb-explorer-public-issues/issues/487
=> fix: halving activated block_number

src/index.css, src/pages/Script/index.tsx, src/pages/Script/styled.tsx, src/pages/Script/styles.module.scss, src/pages/Transaction/TransactionCellScript/index.tsx, src/pages/Transaction/TransactionCellScript/styled.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/450
=> fix(script): script info tab overflow

src/pages/StatisticsChart/activities/CellCount.tsx, src/pages/StatisticsChart/block/AverageBlockTime.tsx, src/pages/StatisticsChart/mining/UncleRate.tsx
1. only show live cell count by default;
2. unify selection of avg-block-time of its thumnail and large chart;
3. offset 1% start point of uncle rate because its initial value makes the chart obsure, similar to an outlier at the start point.
---
Before:
After:
Change in uncle rate chart is not obvious until https://github.com/Magickbase/ckb-explorer-frontend/pull/172 is merged
=> feat: optimize the initial states of charts

src/pages/StatisticsChart/mining/UncleRate.tsx
Before:
After:
Preview: https://ckb-explorer-frontend-in-magickbase-repo-git-ce7281-magickbase.vercel.app/charts/uncle-rate
=> fix: fix auto-scale of y-axis in uncle rate chart

src/pages/StatisticsChart/mining/UncleRate.tsx
Set the right offset larger when it's on mobile
Before:
https://github.com/nervosnetwork/ckb-explorer-frontend/assets/7271329/fb18b802-7d68-4727-8067-32c188dd5e8f
After:
https://github.com/nervosnetwork/ckb-explorer-frontend/assets/7271329/de07d945-ac4b-42e5-aca4-f3547a1c8c20
Ref: https://github.com/Magickbase/ckb-explorer-frontend/pull/173#issuecomment-1851235662
=> fix: fix layout of uncle rate chart

src/pages/Transaction/TransactionComp/TransactionLite/TransactionLite.module.scss, src/pages/Transaction/TransactionComp/TransactionLite/TransactionLite.tsx
According to https://github.com/Magickbase/ckb-explorer-public-issues/issues/503#issuecomment-1870144497, the color of `()` should be the same as `B`
Before:
After:
=> fix: fix color of parentheses in transaction lite list

package.json, src/hooks/useDASAccount.tsx, yarn.lock
Directly downgrading the type will trigger another issue, which was introduced from https://github.com/Magickbase/ckb-explorer-frontend/commit/8b5c2b04db7fa3692a2ea58d06f7aee3ae7f0a8f.
It seems that some misoperations were made to `yarn.lock` during the `merge`, causing subsequent `yarn.lock` to have problems. Therefore, there will be many changes to `yarn.lock` in this PR to fix yarn.lock to the correct path.
=> refactor: downgrade @types/react to a suitable version

src/pages/NftCollectionInfo/NftCollectionInventory/index.tsx, src/pages/NftCollectionInfo/NftCollectionTransfers/index.tsx, src/pages/NftInfo/index.tsx, src/utils/util.ts
Spore Transfers: https://ckb-explorer-frontend-in-magickbase-repo-7s7na2a17-magickbase.vercel.app/nft-collections/0xb8097e2805224610453262e6da554d518c906c1c7ff06741ba45c91c14a7a3d5
Spore Inventory: https://ckb-explorer-frontend-in-magickbase-repo-7s7na2a17-magickbase.vercel.app/nft-collections/0xb8097e2805224610453262e6da554d518c906c1c7ff06741ba45c91c14a7a3d5?tab=inventory
Spore Item: https://ckb-explorer-frontend-in-magickbase-repo-7s7na2a17-magickbase.vercel.app/nft-info/0xb8097e2805224610453262e6da554d518c906c1c7ff06741ba45c91c14a7a3d5/26664864028786808160865657581855065605803054508180609604351482332803080231409
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/546
=> feat: display spore id in hex string format

src/locales/en.json, src/locales/zh.json, src/pages/Tokens/index.tsx, src/pages/Tokens/styles.module.scss
Display a warning icon if an inscription collection uses a name which has been used by formerly issued inscriptions.
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/527
---
Preview: https://ckb-explorer-frontend-in-magickbase-repo-git-0bf4f1-magickbase.vercel.app/inscriptions
=> feat: show warning icon when inscription exist same symbol

src/pages/UDT/index.tsx
The data is not updated when the url of the udt page is updated, this pr fixes this problem
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/540
=> fix: udt page data refresh bug

src/components/Search/index.tsx
The search input component's `onClear` and `onEditEnd` are currently mixed, but the expected response to these two events should be different
reslove: https://github.com/Magickbase/ckb-explorer-public-issues/issues/509
=> fix: Adding onClear to the search input

src/models/UDT/index.ts, src/pages/Tokens/index.tsx, src/pages/UDT/state.ts
Before we use udt's  published attribute to mark a omiga inscription is repeated symbol or not. But the published value was used in other code and confused us. So we add a new attribute in omiga inscription info table to check omiga inscription was repeated or not.
=> feat: use isRepatedSymbol to mark omiga inscription's symbol repeated

package.json, src/pages/Address/AddressComp.tsx, src/pages/Address/BTCAddressComp.tsx, src/pages/Address/styled.tsx, src/pages/Address/styles.module.scss, yarn.lock
1. remove ckb info from btc address page
2. fix style of asset list
Before
After:
=> feat: remove native token info from btc address page

src/styles/index.css
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/537
I checked that the current `tooltip` components are all import from `antd`
and then I see that to be different between `antd` and the `design ui` are the `padding` and `border-radius`.
So I've only changed the style, if there's something else need to change can leave a comment
=> style: adjust tooltip style

src/components/Link/index.tsx
Fix the `Link` component, when using the relative uri, `pathname` property should be used.
=> fix(link): link should not use pathname property when using relative

src/locales/en.json, src/locales/zh.json, src/pages/NftCollections/List.tsx, src/pages/NftCollections/util.ts, src/services/ExplorerService/fetcher.ts
issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/664
=> feat: nft collection sort by timestamp

package.json, src/components/CommonSelect/index.module.scss, src/components/CommonSelect/index.tsx, src/components/ui/Alert.module.scss, src/components/ui/Alert.tsx, src/pages/Error/index.tsx, src/pages/Tools/Hasher/DataToHash.tsx, src/pages/Tools/MoleculeParser/DataInput.tsx, src/pages/Tools/MoleculeParser/Molecule.tsx, src/pages/Tools/MoleculeParser/SchemaSelect.tsx, src/pages/Tools/MoleculeParser/constants.ts, src/pages/Tools/MoleculeParser/index.tsx, src/pages/Tools/MoleculeParser/styles.module.scss, src/pages/Tools/ToolsContainer.tsx, src/pages/Tools/styles.module.scss, src/routes/index.tsx, src/styles/index.css, yarn.lock
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/660
=> feat: add molecule parser tools

src/constants/common.ts, src/locales/en.json, src/locales/zh.json, src/pages/StatisticsChart/activities/CkbHodlWave.tsx, src/pages/StatisticsChart/index.tsx, src/routes/index.tsx, src/services/ExplorerService/fetcher.ts, src/services/ExplorerService/types.ts, src/utils/chart.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/424
=> feat: show ckb hodl wave chart

src/components/Search/AggregateSearchResults.module.scss, src/components/Search/AggregateSearchResults.tsx, src/components/Search/index.tsx, src/components/Search/utils.ts, src/locales/en.json, src/locales/zh.json, src/services/ExplorerService/fetcher.ts, src/services/ExplorerService/types.ts
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/676
=> Fix: search spore result error

src/App.tsx, src/pages/Transaction/TransactionComp/RGBDigestComp.tsx
Currently this page can't get input and output data： https://pudge.explorer.nervos.org/transaction/0x69f3fa734a755aafb4337217b37f27adfc4656be594080bde35fb258e6a28019
This error is due to the `slatetime` of the `queryclient` is set to `infinite`, and when `initialdata` is existed, the `useQuery` will prevent fetch new data
=> fix: updating the `slatetime` to fix the `initialData` causes an prevent fetch data error

src/components/TransactionItem/NodeTransactionItem.tsx, src/components/TransactionItem/TransactionItemCell/NodeTransactionItemCell.tsx, src/components/TransactionItem/TransactionItemCell/index.tsx, src/pages/BlockDetail/BlockComp.tsx, src/pages/BlockDetail/NodeBlockTransactionList.tsx, src/pages/BlockDetail/index.tsx, src/utils/number.ts
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/526
=> feat: block detail page support `node-connect` mode

src/pages/Transaction/TransactionComp/NodeTransactionComp.tsx
Now the cellbase transaction can't display in the tx page in `node-connect` mode, this pr fixes that problem
=> fix: `node-connect` mode cellbase tx display error

src/components/TransactionItem/TransactionItemCell/index.tsx, src/pages/Transaction/TransactionCell/index.tsx, src/utils/cell.ts
Now when the ammount of udt cell is `0`, it will be shown as capacity in the tx / address / block page, this pr is changed to show ammount.
=> fix: udt cell `0` amount not display error

src/components/FilterButton/index.tsx, src/locales/en.json, src/locales/zh.json, src/pages/RGBPP/TransactionList/List/index.tsx, src/pages/RGBPP/TransactionList/List/item.tsx, src/pages/RGBPP/TransactionList/List/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/711
=> feat(rgbpp-list): add others

src/components/Btc/Transaction/index.tsx, src/components/Link/index.tsx, src/components/TransactionItem/TransactionRGBPPDigestModal/TransactionRGBPPDigestContent.tsx, src/components/UTXOGraph/GraphNode/cellNode.tsx, src/pages/Address/AddressPage.tsx, src/pages/Address/RgbppAssets.tsx, src/pages/RGBPP/TransactionList/List/item.tsx, src/pages/Transaction/TransactionCellScript/index.tsx, src/services/BTCIdentifier/index.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/747
=> fix(btc-link): link to the different btc env

src/components/FilterSortContainer/index.module.scss, src/components/MultiFilterButton/index.tsx, src/components/MultiFilterButton/styles.module.scss, src/pages/NftCollections/List.tsx, src/pages/NftCollections/styles.module.scss, src/pages/Xudts/index.tsx, src/pages/Xudts/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/721
=> feat(multi-select): add selected preview

src/assets/small-spinner.svg, src/components/AwesomeLoadings/SmallSpinner/index.tsx, src/components/AwesomeLoadings/SmallSpinner/styles.module.scss, src/components/TransactionItem/TransactionRGBPPDigestModal/TransactionRGBPPDigestContent.module.scss, src/components/TransactionItem/TransactionRGBPPDigestModal/index.tsx, src/components/TransactionItem/TransactionRGBPPDigestModal/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/712
/address/tb1qssu8pscsuevnmvhnr08840wvuzdan27k9m46ja
=> fix(rgb++): loading picture when loading

src/pages/Address/AddressAssetComp.tsx, src/pages/Address/AddressComp.tsx, src/pages/Address/Inscription.tsx, src/pages/Address/MergedAssetList.tsx, src/pages/Address/inscription.module.scss, src/pages/Address/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/536
http://localhost:3000/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq85apn2vnk482lxg8p3uk30r78srnc0aqvyssuun
=> feat(inscription): new ui
