src/components/Card/OverviewCard/styled.tsx, src/pages/Script/ScriptsComp.tsx, src/pages/Script/styles.module.scss, src/pages/Transaction/TransactionCellScript/styled.tsx
Issues: https://github.com/Magickbase/ckb-explorer-public-issues/issues/302
=> fix: the script page style is abnormal.

src/components/TransactionItem/TransactionItemCell/index.tsx, src/pages/Transaction/TransactionCell/index.tsx, src/types/index.d.ts
issues: https://github.com/Magickbase/ckb-explorer-public-issues/issues/222
=> feat: unify extra_info

src/constants/common.ts, src/locales/en.json, src/locales/zh.json, src/pages/StatisticsChart/activities/CellCount.tsx
The result obtained by adding live cells and dead cells together is not accurate when displayed on the chart as "all cells". Therefore, we should update the chart to change it to have three labels (live, dead, all).
=> feat: The Cell Count chart data is abnormal

src/service/http/fetcher.ts
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/373
=> fix: export csv params

src/components/CsvExport/styles.module.scss, src/components/Pagination/styled.tsx, src/components/PaginationWithRear/styles.module.scss, src/pages/SimpleUDT/SimpleUDTComp.tsx, src/pages/SimpleUDT/index.tsx
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/377
Preview:
=> fix: add csv-export btn to sudt page

.gitignore, src/service/http/fetcher.ts
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/387
=> fix: nft download csv path and param

src/__tests__/utils/chart.test.ts, src/pages/StatisticsChart/activities/AddressBalanceRank.tsx, src/pages/StatisticsChart/monetary/Liquidity.tsx, src/pages/StatisticsChart/monetary/TotalSupply.tsx, src/pages/StatisticsChart/nervosDao/NewDaoDeposit.tsx, src/pages/StatisticsChart/nervosDao/TotalDaoDeposit.tsx, src/utils/chart.ts
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/381
=> chore: optimize chart unit display

src/pages/Address/AddressComp.tsx, src/pages/Address/index.tsx
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/409
=> fix: address lost when go to export page

src/service/http/fetcher.ts
Related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/406
=> fix: add end date by nearly one day when download csv

src/pages/Transaction/TransactionCellList/index.tsx, src/pages/Transaction/TransactionCellList/styled.tsx
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/411
=> fix: double tx title on chrome@103

src/pages/ExportTransactions/index.tsx
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/410
=> feat: disable download btn when downloading

package.json, yarn.lock
Reverts Magickbase/ckb-explorer-frontend#78
=> Revert "fix(deps): update dependency three to v0.155.0"

src/pages/NervosDao/index.tsx, src/pages/NervosDao/styled.tsx
=> fix: fix mobile layout of nervos dao page

src/pages/SimpleUDT/SimpleUDTComp.tsx
Resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/413
=> fix: show download button when only one page of content on sUDT page

src/pages/Script/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/72#event-10268663017
=> feat(script-info): add refererring cells tab to script info page.

src/App.tsx, src/components/Card/TitleCard/index.tsx, src/components/NftCollectionTransfers/styles.module.scss, src/components/NftHolderList/styles.module.scss, src/components/Search/Filter/styled.tsx, src/components/TransactionItem/TransactionLiteItem/index.module.scss, src/index.css, src/index.tsx, src/pages/Address/styles.module.scss, src/pages/BlockDetail/BlockComp.tsx, src/pages/BlockDetail/styles.module.scss, src/pages/ExportTransactions/index.tsx, src/pages/ExportTransactions/styles.module.scss, src/pages/Home/AverageBlockTimeChart/styled.tsx, src/pages/Home/HashRateChart/styled.tsx, src/pages/NftCollections/List.tsx, src/pages/NftCollections/styles.module.scss, src/pages/Script/ScriptsComp.tsx, src/pages/Script/styles.module.scss, src/pages/Tokens/styled.tsx
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/432
~~Based on PR #103~~
=> Refactor: Remove !important used in CSS

src/routes/index.tsx, src/types/index.d.ts
And remove `CustomRouter` in the `index.d.ts`
It should be noted that I removed a piece of logic that I thought was not useful. @Keith-CY needs to confirm this: https://github.com/nervosnetwork/ckb-explorer-frontend/commit/466fb752a68ee667f9b47354a09839c2864e7a65#diff-3d4d2177c21702138c6c0473b20d38d819dec2249dd99cbf1d00fde1f6ac5115L396-L398
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/434
~~Based on PR #103~~
=> Refactor: optimize and simplify the routes code

src/pages/Transaction/TransactionCellScript/index.tsx, src/types/index.d.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/446
=> fix(cell): use occupied capacity from api directly

src/components/Card/HashCard/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/454
=> fix(tx-card): copy button not work

src/constants/scripts.ts, src/locales/en.json, src/locales/zh.json, src/pages/ScriptList/index.tsx
Resolves: https://github.com/Magickbase/ckb-explorer-public-issues/issues/123
=> chore: update joyid info

src/locales/en.json, src/locales/zh.json, src/pages/Transaction/TransactionComp/TransactionLite/TransactionLite.tsx
Fix the transfer amount decimals of transaction lite panel
=> fix: transfer udt amount decimals

src/pages/Tokens/index.tsx
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/453
~~PR based on https://github.com/Magickbase/ckb-explorer-frontend/pull/126~~
=> Modify the default sorting of the tokens page

src/pages/StatisticsChart/activities/BalanceDistribution.tsx, src/pages/StatisticsChart/mining/DifficultyHashRate.tsx, src/pages/StatisticsChart/monetary/TotalSupply.tsx, src/pages/StatisticsChart/nervosDao/NewDaoDeposit.tsx, src/pages/StatisticsChart/nervosDao/TotalDaoDeposit.tsx, src/utils/chart.ts
1. the assertion function of type of charts is wrong
2. the type of charts toolltip data must be converted from number to string
This PR is to solve the issue https://github.com/Magickbase/ckb-explorer-public-issues/issues/461
=> fix(charts): type of charts tooltip data is wrong

src/pages/StatisticsChart/mining/DifficultyUncleRateEpoch.tsx
The type of data is number, but it's asserted to be string while exception is not properly handled
=> fix: fix frozen epoch time chart

src/constants/scripts.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/123#issuecomment-1800846202
=> feat: add JoyID testnet

src/pages/Home/AverageBlockTimeChart/index.tsx, src/pages/Home/HashRateChart/index.tsx, src/pages/StatisticsChart/activities/AddressBalanceRank.tsx, src/pages/StatisticsChart/activities/AddressCount.tsx, src/pages/StatisticsChart/activities/BalanceDistribution.tsx, src/pages/StatisticsChart/activities/CellCount.tsx, src/pages/StatisticsChart/activities/TransactionCount.tsx, src/pages/StatisticsChart/activities/TxFeeHistory.tsx, src/pages/StatisticsChart/block/AverageBlockTime.tsx, src/pages/StatisticsChart/block/BlockTimeDistribution.tsx, src/pages/StatisticsChart/block/EpochTimeDistribution.tsx, src/pages/StatisticsChart/common/index.tsx, src/pages/StatisticsChart/mining/Difficulty.tsx, src/pages/StatisticsChart/mining/DifficultyHashRate.tsx, src/pages/StatisticsChart/mining/DifficultyUncleRateEpoch.tsx, src/pages/StatisticsChart/mining/HashRate.tsx, src/pages/StatisticsChart/mining/MinerAddressDistribution.tsx, src/pages/StatisticsChart/mining/MinerVersionDistribution.tsx, src/pages/StatisticsChart/mining/UncleRate.tsx, src/pages/StatisticsChart/monetary/AnnualPercentageCompensation.tsx, src/pages/StatisticsChart/monetary/InflationRate.tsx, src/pages/StatisticsChart/monetary/Liquidity.tsx, src/pages/StatisticsChart/monetary/SecondaryIssuance.tsx, src/pages/StatisticsChart/monetary/TotalSupply.tsx, src/pages/StatisticsChart/nervosDao/CirculationRatio.tsx, src/pages/StatisticsChart/nervosDao/NewDaoDeposit.tsx, src/pages/StatisticsChart/nervosDao/TotalDaoDeposit.tsx, src/utils/hook.ts
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/202
~~Based on PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/134~~
=> Refactored chart cache from localstroage-based to http-based

src/utils/number.ts
Resolves: https://github.com/Magickbase/ckb-explorer-public-issues/issues/459
=> fix: parse udt value negative issue

src/pages/Transaction/TransactionComp/TransactionOverview.tsx, src/pages/Transaction/TransactionComp/styled.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/458
=> fix(transaction): align in transaction parameter

.eslintrc.js, .storybook/main.ts, .storybook/preview.ts, package.json, src/components/AddressText/index.stories.module.scss, src/components/AddressText/index.stories.tsx, src/components/EllipsisMiddle/index.stories.tsx, src/components/EllipsisMiddle/index.tsx, src/utils/hook.ts, src/utils/i18n.ts, yarn.lock
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/480
This is a part of the implementation, the remaining stories implementation will be done in conjunction with https://github.com/Magickbase/ckb-explorer-public-issues/issues/479 and https://github.com/Magickbase/ckb-explorer-public-issues/issues/481
~~Based on PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/143~~
=> Import Storybook

src/components/Banner/HalvingBanner.tsx, src/pages/Halving/index.tsx, src/utils/hook.ts
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/483
=> chore: optimize halving countdown time calcu

src/pages/StatisticsChart/activities/BalanceDistribution.tsx, src/pages/StatisticsChart/block/AverageBlockTime.tsx, src/pages/StatisticsChart/nervosDao/NewDaoDeposit.tsx, src/pages/StatisticsChart/nervosDao/TotalDaoDeposit.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/482
=> fix(chart): multiple tick marks in chat

src/components/DecimalCapacity/styled.tsx, src/components/DecimalCapacity/styles.module.scss, src/pages/NervosDao/DaoOverview/index.tsx, src/pages/NervosDao/DaoOverview/styled.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/474
=> fix(dao): chart style in mobile

src/pages/Script/ScriptsComp.tsx, src/pages/Script/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/439
=> feat(script): Not reload on focus while 404

src/pages/Script/ScriptsComp.tsx, src/pages/Script/styles.module.scss
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/499
=> fix: styles for the script page

src/constants/scripts.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/510#issuecomment-1882446040
=> feat: add mainnet deployment info of xUDT

src/pages/BlockDetail/BlockComp.tsx, src/pages/BlockDetail/index.tsx, src/utils/util.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/477
=> fix(block): load last block info while loading next or previous

src/locales/en.json, src/locales/zh.json, src/models/Address/UDTAccount.ts, src/pages/Address/AddressAssetComp.tsx, src/pages/Address/AddressComp.tsx, src/pages/Address/styled.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/516
=> feat(inscription): add inscription to the address card

src/locales/en.json, src/locales/zh.json, src/pages/Address/AddressComp.tsx, src/pages/Address/styled.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/524
=> fix(inscription): ink should be more shorter when language changed

src/components/Search/index.module.scss, src/components/Search/index.tsx, src/components/Search/spinner.svg
Resolves: https://github.com/Magickbase/ckb-explorer-public-issues/issues/512
https://github.com/Magickbase/ckb-explorer-frontend/assets/3870972/b91ec13d-1d0b-41cc-aa15-dc73d87bae17
=> Fix: loading state of search input

src/constants/scripts.ts, src/pages/ScriptList/index.tsx
Deployment info: https://github.com/sporeprotocol/spore-sdk/blob/beta/packages/core/src/config/predefined.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/535
=> feat: add deployment info of spore

src/pages/NftCollections/List.tsx, src/services/ExplorerService/fetcher.ts
Ref: https://github.com/nervosnetwork/ckb-explorer/pull/1651
=> feat: use sn as unique items virtual type script hash

src/components/Search/index.tsx, src/models/Transaction/index.ts, src/services/ExplorerService/fetcher.ts
1. When the input is btc address, go to the address page
2. When the input is btc tx, goto tx page.
=> feat: Support btc tx and address

src/components/Modal/styled.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/590#issuecomment-2026727812
=> fix(rgb++): fix the search button over the modal

src/components/Header/index.tsx
reslove: https://github.com/Magickbase/ckb-explorer-public-issues/issues/572
=> fix: mobile menu was not hidden when change the page 

src/components/Header/SearchComp/index.tsx, src/components/Search/index.tsx, src/pages/Transaction/TransactionCell/index.tsx, src/utils/rgbpp.ts
reslove: https://github.com/Magickbase/ckb-explorer-public-issues/issues/573
=> fix: keyboard buttons will fail to submit data.

src/constants/scripts.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/606
=> feat: update testnet deployment info of unique cell

src/components/Header/SearchComp/index.tsx, src/components/Search/index.tsx
reslove: https://github.com/Magickbase/ckb-explorer-public-issues/issues/573#issuecomment-2034113563
=> feat: search box will select first when press enter on `byname`

src/components/Content/index.tsx, src/pages/Transaction/index.tsx
reslove: https://github.com/Magickbase/ckb-explorer-public-issues/issues/533
=> fix: `show row` ui error

src/components/XUDTTag/index.tsx, src/components/XUDTTag/styles.module.scss, src/locales/en.json, src/locales/zh.json, src/models/Xudt/index.ts, src/pages/Xudt/UDTComp.tsx, src/pages/Xudt/styles.module.scss, src/pages/Xudts/index.tsx, src/pages/Xudts/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/620
=> feat(xudttag): add xudt tags

src/pages/Transaction/TransactionComp/TransactionDetailsHeader.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/635
=> fix(digest): add margin-top for btc tx

yarn.lock
Reverts Magickbase/ckb-explorer-frontend#312
=> Revert "chore(deps): update dependency @types/react-test-renderer to v18.3.0"

src/components/Btc/Transaction/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/634
=> fix(btc): wrong direction when click the input address

src/components/AddressText/index.tsx, src/components/TransactionItem/TransactionRGBPPDigestModal/TransactionRGBPPDigestContent.tsx, src/components/TransactionItem/TransactionRGBPPDigestModal/styles.module.scss, src/pages/Transaction/TransactionComp/TransactionDetailsHeader.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/648
=> fix(digest): mobile abnormal digest padding

src/locales/zh.json, src/pages/XudtExport/index.tsx, src/pages/XudtExport/styles.module.scss, src/utils/i18n.ts
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/641#issuecomment-2128500964
=> Chore: optimize xudt export page

src/assets/redirect-icon.svg, src/components/AddressText/styles.module.scss, src/components/TransactionItem/TransactionRGBPPDigestModal/TransactionRGBPPDigestContent.tsx, src/components/TransactionItem/TransactionRGBPPDigestModal/styles.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/639
=> feat(digest): add redirect link to bitcoin explorer

src/components/TransactionItem/TransactionItemCell/index.tsx, src/components/TransactionItem/TransactionRGBPPDigestModal/TransactionRGBPPDigestTransferAsset.tsx, src/locales/zh.json, src/models/Address/UDTAccount.ts, src/models/Cell/index.ts, src/models/UDT/index.ts, src/pages/Address/AddressAssetComp.tsx, src/pages/Address/DefinedTokens.tsx, src/pages/Tokens/index.tsx, src/pages/Transaction/TransactionCell/index.tsx, src/pages/UDT/UDTComp.tsx, src/services/ExplorerService/fetcher.ts, src/services/ExplorerService/types.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/683
=> refactor: remove udt's uan and display_name attributes

src/locales/en.json, src/locales/zh.json, src/pages/StatisticsChart/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/713
https://ckb-explorer-frontend-in-magickbase-repo-git-43df9e-magickbase.vercel.app/charts
=> fix(statistic): description abnormal

src/models/Xudt/index.ts, src/pages/Xudt/HolderAllocation.module.scss, src/pages/Xudt/HolderAllocation.tsx, src/pages/Xudt/UDTComp.tsx, src/pages/Xudt/index.tsx, src/pages/Xudts/index.tsx, src/services/ExplorerService/fetcher.ts, src/utils/util.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/697#issuecomment-2188352232
=> feat(holder-allocation): add new api

src/components/Footer/index.tsx, src/components/Footer/open.svg, src/components/Footer/styled.tsx
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/677
=> feat: add "Powered by MagicKBase" text

src/pages/RGBPP/TransactionList/List/index.tsx, src/pages/RGBPP/TransactionList/List/item.tsx, src/pages/RGBPP/TransactionList/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/711
=> feat(rgb): type update for rgb transaction

src/components/Header/CKBNodeComp/CKBNodeModal.tsx, src/components/Header/CKBNodeComp/style.module.scss, src/components/Header/LanguageComp/LanguageModal.tsx, src/components/Header/LanguageComp/style.module.scss
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/709
=> chore: remove `Done` button

src/pages/Address/RgbppAssets.tsx, src/pages/Address/rgbppAssets.module.scss
https://github.com/Magickbase/ckb-explorer-public-issues/issues/719
=> fix(assets): cell width

src/components/MultiFilterButton/index.tsx
=> feat(multi-select): change the rule

src/pages/Transaction/TransactionCellList/styled.tsx
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/738
=> styling: adjust transaction cell header style

src/locales/en.json, src/locales/zh.json, src/models/Xudt/index.ts, src/pages/Xudt/HolderAllocation.module.scss, src/pages/Xudt/HolderAllocation.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/731
https://ckb-explorer-frontend-in-magickbase-repo-git-c8fec5-magickbase.vercel.app/xudt/0xcf7801c056d3660f1520dd16925c3746d474456199d48ab16cf8af9d6cb80128
=> feat(allocation): add jump link to holder allocation

src/pages/Address/Cells.tsx, src/services/ExplorerService/types.ts
https://github.com/Magickbase/ckb-explorer-public-issues/issues/640#issuecomment-2132601398
=> feat(live-cell): add link to asset name in live cell

src/pages/BlockDetail/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/753
=> fix(block): extra null block request

src/pages/Address/Cells.tsx, src/services/ExplorerService/fetcher.ts
https://github.com/nervosnetwork/ckb-explorer-frontend/issues/1742
=> fix(live-cell): not filter bound status when using ckb address

src/pages/Script/index.tsx, src/pages/Script/styles.module.scss
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/722
=> feat: add header card for script detail page

src/pages/Script/ScriptsComp.tsx
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/767
=> fix: script detail page missing error message

src/pages/NftCollectionInfo/NftCollectionOverview/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/760
=> fix(nft): description is an object

src/pages/UDT/UDTComp.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/557
=> feat(inscription): no record

src/components/Search/HighlightText.tsx, src/components/XUDTTag/index.tsx, src/components/XUDTTag/styles.module.scss, src/hooks/useCKBNode.tsx, src/locales/en.json, src/locales/zh.json, src/pages/Xudt/UDTComp.tsx
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/762
=> fix: xudt detail page tag button not working

src/pages/BlockDetail/index.tsx, src/services/ExplorerService/index.ts, src/utils/address.ts, src/utils/number.ts
resolved: https://github.com/Magickbase/ckb-explorer-public-issues/issues/777
=> fix: ExplorerService missing error handling cause page crash

src/components/XUDTTag/index.tsx
https://github.com/Magickbase/ckb-explorer-public-issues/issues/778
=> fix(tag): jump url

src/components/TransactionParameters/index.tsx, src/models/Transaction/index.ts, src/pages/Transaction/state.ts, src/utils/transformer.ts
=> feat: cell_deps api

src/locales/en.json, src/locales/zh.json, src/pages/Address/AddressComp.tsx, src/pages/Address/AddressPage.tsx, src/pages/Address/styles.module.scss, src/pages/Script/ScriptsComp.tsx, src/pages/Script/styles.module.scss, src/services/ExplorerService/fetcher.ts, src/services/ExplorerService/types.ts
related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/785
=> chore: add overcount notice

src/locales/en.json, src/locales/zh.json, src/pages/Address/AddressPage.tsx, src/pages/Script/ScriptsComp.tsx, src/pages/Script/index.tsx
related: https://github.com/Magickbase/ckb-explorer-public-issues/issues/785#issuecomment-2574289590
=> chore: change overlimit notice text

src/pages/Address/AddressPage.tsx
issue:
- https://github.com/Magickbase/ckb-explorer-public-issues/issues/819
=> fix: The address's Transactions count is incorrect after sending a transaction

src/pages/HardFork/index.tsx, src/pages/HardFork/styles.module.scss
chore: add change overlimit notice1. add colons between digital numbers
2. update progres bar based on the remaining time
3. update style of progress bar markers
---
Before
After
=> feat: implement hardfork page

src/components/TransactionItem/styled.tsx, src/locales/en.json, src/locales/zh.json, src/pages/Script/ScriptsComp.tsx, src/pages/Script/index.tsx, src/pages/Script/styles.module.scss, src/services/ExplorerService/fetcher.ts
The UI adjustment needs @PainterPuppets  to finish.
=> feat: add restrict mode for script transactions
